try to fix compiling issue of clebsch project by 1. changing .cpp files to .cu 2. commenting out all usage of Eigen incompletecholesky 3. commenting out usage of json since it will include the common file in Meso library, which leads to multiple definition of VectorD in Macro
current issue: unknown location of error Severity Code Description Project File Line Suppression State
Error  C:\Users\fanfe\AppData\Local\.xmake\packages\e\eigen\3.4.0\96d56db5bdde4df1aa91275a485e2837\include\eigen3\Eigen\src/Core/Ref.h(332): error C2248: 'Eigen::RefBase<Eigen::Ref<const Eigen::Matrix<double,-1,1,0,4096,1>,0,Eigen::InnerStride<1>>>::StrideType': cannot access private typedef declared in class 'Eigen::RefBase<Eigen::Ref<const Eigen::Matrix<double,-1,1,0,4096,1>,0,Eigen::InnerStride<1>>>' fluid_euler_two_phase_clebsch D:\fanfe\meso\build\fluid_euler_two_phase_clebsch\vsxmake2022\fluid_euler_two_phase_clebsch\EXEC 1